name: cyber_fraud_simulator
description: CEP Cyber Security & Fraud Simulator App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  pdf: ^3.10.8
  printing: ^5.12.0
  http: ^1.2.0

flutter:
  uses-material-design: true
